name = "collection-kit-stats"
main = "src/worker.js"
compatibility_date = "2026-05-05"

[[d1_databases]]
binding = "DB"
database_name = "collection-kit-stats"
database_id = "3e18385a-af83-4c67-83a0-ab889149692c"

[vars]
ALLOWED_ORIGINS = "https://just-goforward.github.io"
